#!/usr/bin/env python3
"""Generate the RPC-merged config sets from the reference ones.

The RPC-merged study (``rpc_merge: true`` in ``columns.yaml``) clusters the
barrel RPC rechits together with DT and the endcap RPC rechits together with
CSC, so the run has only CSC and DT clusters -- every RPC rechit is already
inside one of them -- and each cluster carries an RPC-derived time.  Its
configs are the reference ones with three mechanical edits:

* every block that mentions ``events.rpcCluster`` or ``llp.recoRPC`` is
  dropped, along with the histograms and derived plots that referenced it
  (there is no standalone RPC cluster collection any more);
* the per-LLP hit counts that define "reconstructable in this system" gain the
  RPC region that was merged into it (``nHitsCSC + nHitsRPCEndcap``,
  ``nHitsDT + nHitsRPCBarrel``);
* the RPC content and RPC timing of the merged clusters are added as new
  histograms (see :data:`RPC_HISTOGRAMS`).

Writing them out rather than hand-maintaining a second copy keeps the shared
plots -- binning, isolation cuts, variant splits -- identical to the reference
study by construction, which is what makes the two runs comparable.

    python scripts/make_rpcmerge_configs.py          # write the config dirs
    python scripts/make_rpcmerge_configs.py --check   # verify they are current
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIGS = REPO / "configs"

# generated set -> reference set it is derived from
SOURCES = {
    "configs_mds_rpcmerge": "configs_mds_grid",            # signal grid, truth
    "configs_mds_rpcmerge_data": "configs_mds_data",        # reco-only, + data
}

# A block mentioning any of these describes something the merged run does not
# produce: the standalone RPC cluster collection, or an LLP field derived from
# it.  Histograms and derived plots that referenced such a block are dropped
# with it (see _prune).
DEAD_TOKENS = ("events.rpcCluster", "events.llp.recoRPC",
               "events.llp.nRecoClusterRPC", "events.llp.clusterHitFracRPC",
               "rpc_variants", "rpc_iso")

# Sub-blocks of the histograms' `_variant_sets:` mapping that go with them.
DEAD_VARIANT_SETS = ("rpc_iso", "rpc_variants")

# "Rechits of this LLP in this system" now includes the RPC region that was
# merged into the system, both in the selections and in the histograms.
HIT_COUNT_REWRITES = (
    ("events.llp.nHitsCSC", "(events.llp.nHitsCSC + events.llp.nHitsRPCEndcap)"),
    ("events.llp.nHitsDT", "(events.llp.nHitsDT + events.llp.nHitsRPCBarrel)"),
)
# Header comments of the reference sets that name the three cluster
# collections; the merged run has two.
COMMENT_REWRITES = (
    ("custom/columns.py: events.llp, events.cscCluster, events.dtCluster,\n"
     "# events.rpcCluster.",
     "custom/columns.py: events.llp, events.cscCluster, events.dtCluster\n"
     "# (the RPC rechits are clustered inside those two, see rpc_merge)."),
    ("(events.cscCluster / dtCluster / rpcCluster)",
     "(events.cscCluster / dtCluster; the RPC rechits are clustered inside\n"
     "# those two, see rpc_merge)"),
)

LABEL_REWRITES = (
    (r"N_{\mathrm{CSC\ rechits}}", r"N_{\mathrm{CSC+RPC\ rechits}}"),
    (r"N_{\mathrm{DT\ rechits}}", r"N_{\mathrm{DT+RPC\ rechits}}"),
)

# "Where in CSC / DT does the cluster start" is what these histograms mean, and
# a cluster whose innermost hit is an RPC one has no chamber code on that
# scale (it is offset by +1000, i.e. in the overflow bin, which the plotting
# folds into the last one).  Cut those clusters instead of piling them up
# there -- <sys>_cluster_first_system is where they are counted.
SELECTION_INJECTIONS = {
    "csc_cluster_first_chamber": "csc_cluster_first_not_rpc",
    "csc_cluster_first_station": "csc_cluster_first_not_rpc",
    "dt_cluster_first_chamber": "dt_cluster_first_not_rpc",
    "dt_cluster_first_station": "dt_cluster_first_not_rpc",
}

COLUMNS_NOTE = """
  # The RPC rechits are clustered with the system they overlap -- barrel RPC
  # (Region == 0) with DT, endcap RPC with CSC -- instead of on their own, so
  # this run has cscCluster and dtCluster only and each of them carries the RPC
  # timing of its own hits (rpcTime*).  rpc_min_samples is unused here: both
  # merged systems use cluster_min_samples.
  rpc_merge: true
"""

GENERATED_HEADER = """\
# GENERATED by scripts/make_rpcmerge_configs.py from configs/{source}/ --
# edit that config set (or the generator) and re-run, do not edit this file.
#
"""

# ── The new histograms: what the merged clusters gained ────────────
# One copy per merged system, with that system's variant split so the
# matched / unmatched / isolated versions come for free.
RPC_HISTOGRAMS = """
# ── RPC content and RPC timing of the merged clusters ─────────────
# Filled from the RPC rechits that DBSCAN put inside a {SYS} cluster
# (custom/clustering.py, rpc_merge).  The time fields are NaN on a cluster
# with no RPC hit, so every one of them is filtered by {sys}_cluster_has_rpc.
# NOTE the rechit time itself (rpcTime*) is unfilled in every MDSNano
# production so far -- rpcRecHits_Time is 0 with TimeError -1, so those fields
# are NaN and their histograms come out empty by construction.  The bunch
# crossing (rpcBx*) is the timing that is actually there.
{sys}_cluster_n_rpc_hits:
  expression: "events.{sys}Cluster.nRPCHits"
  per_object: true
  bins: 50
  lo: 0
  hi: 100
  label: '{SYS} cluster $N_{{\\mathrm{{RPC\\ hits}}}}$'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_n_rpc_hits_bx0:
  expression: "events.{sys}Cluster.nRPCHitsBx0"
  per_object: true
  bins: 50
  lo: 0
  hi: 100
  label: '{SYS} cluster $N_{{\\mathrm{{RPC\\ hits}}}}$ at BX 0'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_rpc_hit_frac:
  expression: "events.{sys}Cluster.rpcHitFrac"
  per_object: true
  bins: 50
  lo: 0
  hi: 1
  label: '{SYS} cluster RPC hit fraction'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_first_system:
  expression: "events.{sys}Cluster.firstSystem"
  per_object: true
  bins: 3
  lo: 0
  hi: 3
  label: '{SYS} cluster innermost hit system (0 CSC, 1 DT, 2 RPC)'
  variants: {sys}_variants

{sys}_cluster_rpc_time:
  expression: "events.{sys}Cluster.rpcTime"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 60
  lo: -30
  hi: 30
  label: '{SYS} cluster RPC time [ns]'
  variants: {sys}_variants

{sys}_cluster_rpc_time_median:
  expression: "events.{sys}Cluster.rpcTimeMedian"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 60
  lo: -30
  hi: 30
  label: '{SYS} cluster RPC time (median) [ns]'
  variants: {sys}_variants

{sys}_cluster_rpc_time_weighted:
  expression: "events.{sys}Cluster.rpcTimeWeighted"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 60
  lo: -30
  hi: 30
  label: '{SYS} cluster RPC time ($1/\\sigma^2$-weighted) [ns]'
  variants: {sys}_variants

{sys}_cluster_rpc_time_spread:
  expression: "events.{sys}Cluster.rpcTimeSpread"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 50
  lo: 0
  hi: 25
  label: '{SYS} cluster RPC time RMS [ns]'
  variants: {sys}_variants

{sys}_cluster_rpc_time_err:
  expression: "events.{sys}Cluster.rpcTimeErr"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 50
  lo: 0
  hi: 5
  label: '{SYS} cluster RPC time uncertainty [ns]'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_rpc_bx:
  expression: "events.{sys}Cluster.rpcBx"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 9
  lo: -4.5
  hi: 4.5
  label: '{SYS} cluster mean RPC BX'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_rpc_time_valid_frac:
  expression: "events.{sys}Cluster.rpcTimeValidFrac"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 50
  lo: 0
  hi: 1
  label: '{SYS} cluster fraction of RPC hits with a valid time'
  log_y: true
  variants: {sys}_variants

# The bunch crossing is the timing that IS filled in the current MDSNano
# productions (rpcRecHits_Time is 0 with TimeError -1 throughout), so this is
# the RPC time estimate to read today: 25 ns per BX.
{sys}_cluster_rpc_time_from_bx:
  expression: "events.{sys}Cluster.rpcBx * 25"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 40
  lo: -100
  hi: 100
  label: '{SYS} cluster RPC time from BX [ns]'
  variants: {sys}_variants

{sys}_cluster_rpc_bx_median:
  expression: "events.{sys}Cluster.rpcBxMedian"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 9
  lo: -4.5
  hi: 4.5
  label: '{SYS} cluster median RPC BX'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_rpc_bx_spread:
  expression: "events.{sys}Cluster.rpcBxSpread"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 40
  lo: 0
  hi: 4
  label: '{SYS} cluster RPC BX RMS'
  log_y: true
  variants: {sys}_variants

{sys}_cluster_rpc_out_of_time_frac:
  expression: "events.{sys}Cluster.rpcOutOfTimeFrac"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins: 50
  lo: 0
  hi: 1
  label: '{SYS} cluster out-of-time RPC hit fraction'
  log_y: true
  variants: {sys}_variants

# Timing vs the cluster size and vs where it sits: a genuine displaced shower
# is both large and late, a prompt one large and in time.
{sys}_cluster_rpc_bx_vs_size:
  expression_x: "events.{sys}Cluster.size"
  expression_y: "events.{sys}Cluster.rpcBx"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins_x: 50
  lo_x: 0
  hi_x: 500
  bins_y: 9
  lo_y: -4.5
  hi_y: 4.5
  label_x: '{SYS} cluster $N_{{\\mathrm{{hits}}}}$'
  label_y: '{SYS} cluster mean RPC BX'
  log_z: true

{sys}_cluster_rpc_time_vs_size:
  expression_x: "events.{sys}Cluster.size"
  expression_y: "events.{sys}Cluster.rpcTime"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins_x: 50
  lo_x: 0
  hi_x: 500
  bins_y: 60
  lo_y: -30
  hi_y: 30
  label_x: '{SYS} cluster $N_{{\\mathrm{{hits}}}}$'
  label_y: '{SYS} cluster RPC time [ns]'
  log_z: true

{sys}_cluster_rpc_time_vs_nrpc:
  expression_x: "events.{sys}Cluster.nRPCHits"
  expression_y: "events.{sys}Cluster.rpcTime"
  per_object: true
  selections: [{sys}_cluster_has_rpc]
  bins_x: 50
  lo_x: 0
  hi_x: 100
  bins_y: 60
  lo_y: -30
  hi_y: 30
  label_x: '{SYS} cluster $N_{{\\mathrm{{RPC\\ hits}}}}$'
  label_y: '{SYS} cluster RPC time [ns]'
  log_z: true
"""

# The out-of-time-background handles that come from the rechit time itself.
# CSC only -- DT rechits have no time branch, so a DT cluster is timed through
# its RPC hits instead (the rpcBx* fields above).
CSC_TIME_HISTOGRAMS = """
# ── CSC cluster timing: the out-of-time pile-up handles ───────────
# A genuine shower puts every hit at one time; a cluster DBSCAN assembled out
# of unrelated in-time and out-of-time hits is spread out.  csc_cluster_time
# (the mean) is above, with the reference study's binning.
csc_cluster_time_spread:
  expression: "events.cscCluster.timeSpread"
  per_object: true
  bins: 50
  lo: 0
  hi: 50
  label: 'CSC cluster $t_{\\mathrm{peak}}$ RMS [ns]'
  log_y: true
  variants: csc_variants

csc_cluster_oot_hit_frac:
  expression: "events.cscCluster.ootHitFrac"
  per_object: true
  bins: 50
  lo: 0
  hi: 1
  label: 'CSC cluster out-of-time hit fraction ($|t_{\\mathrm{peak}}| > 12.5$ ns)'
  log_y: true
  variants: csc_variants

# The plane the in-time selection is drawn in.
csc_cluster_time_vs_spread:
  expression_x: "events.cscCluster.time"
  expression_y: "events.cscCluster.timeSpread"
  per_object: true
  bins_x: 60
  lo_x: -30
  hi_x: 90
  bins_y: 50
  lo_y: 0
  hi_y: 50
  label_x: 'CSC cluster mean $t_{\\mathrm{peak}}$ [ns]'
  label_y: 'CSC cluster $t_{\\mathrm{peak}}$ RMS [ns]'
  log_z: true
"""

RPC_SELECTIONS = """
# ── RPC content of a merged cluster ───────────────────────────────
# The rpcTime* fields are NaN on a cluster that picked up no RPC rechit (a
# comparison against NaN is False, so those clusters would be dropped
# silently); this mask says so explicitly.
csc_cluster_has_rpc:
  level: object
  expression: "events.cscCluster.nRPCHits > 0"
dt_cluster_has_rpc:
  level: object
  expression: "events.dtCluster.nRPCHits > 0"

# The cluster's innermost hit is one of the primary system's, so its
# firstChamber / firstStation read on that system's scale (see
# SELECTION_INJECTIONS in the generator).  firstSystem codes: 0 CSC, 1 DT,
# 2 RPC.
csc_cluster_first_not_rpc:
  level: object
  expression: "events.cscCluster.firstSystem != 2"
dt_cluster_first_not_rpc:
  level: object
  expression: "events.dtCluster.firstSystem != 2"
"""

# Timing profiles, for the truth-carrying set only: how the RPC time tracks
# the LLP's decay position.
RPC_DERIVED_PLOTS = """
# ── RPC timing of the merged clusters ─────────────────────────────
# The BX profiles are the ones with data in the current productions; the
# rechit-time profiles stay for a production that fills rpcRecHits_Time.
prof_csc_rpc_bx_vs_size:
  type: profile_x
  source: csc_cluster_rpc_bx_vs_size
  label_x: 'CSC cluster $N_{\\mathrm{hits}}$'
  label_y: '$\\langle$RPC BX$\\rangle$'
prof_dt_rpc_bx_vs_size:
  type: profile_x
  source: dt_cluster_rpc_bx_vs_size
  label_x: 'DT cluster $N_{\\mathrm{hits}}$'
  label_y: '$\\langle$RPC BX$\\rangle$'
prof_csc_rpc_time_vs_size:
  type: profile_x
  source: csc_cluster_rpc_time_vs_size
  label_x: 'CSC cluster $N_{\\mathrm{hits}}$'
  label_y: '$\\langle$RPC time$\\rangle$ [ns]'
prof_dt_rpc_time_vs_size:
  type: profile_x
  source: dt_cluster_rpc_time_vs_size
  label_x: 'DT cluster $N_{\\mathrm{hits}}$'
  label_y: '$\\langle$RPC time$\\rangle$ [ns]'
"""


def _blocks(text, indent=0):
    """Split a YAML document into ``(key, text)`` blocks at one indent level.

    A block is a key at ``indent``, everything indented under it, and the
    comment lines immediately above it (a comment separated from the key by a
    blank line describes the section that follows, so it goes with the new
    block; the blank line closes the old one).  The text before the first key
    comes back as a block with key None, and concatenating every block
    reproduces the input exactly.
    """
    key_re = re.compile(r"^ {%d}([A-Za-z_][\w.-]*):" % indent)
    blocks, key, current, pending = [], None, [], []
    for line in text.splitlines(keepends=True):
        match = key_re.match(line)
        if match:
            # Split the run of comment/blank lines above at its last blank
            # line: what is before closes this block, what is after opens the
            # next one.
            keep = len(pending) - next(
                (i for i, l in enumerate(reversed(pending)) if not l.strip()),
                len(pending))
            current.extend(pending[:keep])
            blocks.append((key, "".join(current)))
            key, current, pending = match.group(1), pending[keep:] + [line], []
        elif line.strip().startswith("#") or not line.strip():
            pending.append(line)
        else:
            current.extend(pending)
            current.append(line)
            pending = []
    current.extend(pending)
    blocks.append((key, "".join(current)))
    return blocks


def _prune(text, is_dead, indent=0):
    """Drop the blocks of ``text`` whose body ``is_dead``; return (text, keys)."""
    kept, dropped = [], []
    for key, body in _blocks(text, indent):
        if key is not None and is_dead(key, body):
            dropped.append(key)
        else:
            kept.append(body)
    return "".join(kept), dropped


def _mentions(body, names):
    """Does the block body reference any of these YAML keys / tokens?

    A name also matches its variant-expanded forms (``rpc_cluster_size`` ->
    ``rpc_cluster_size_matched``), which is how a derived plot built on a
    variant of a dropped histogram is dropped too.
    """
    return any(re.search(r"(?<![\w.])%s(?:_\w+)?(?![\w])" % re.escape(name), body)
               for name in names)


def _prune_variant_sets(text):
    """Drop the RPC entries of the histograms' ``_variant_sets:`` mapping."""
    out = []
    for key, body in _blocks(text):
        if key == "_variant_sets":
            lines = body.splitlines(keepends=True)
            i = next(j for j, l in enumerate(lines) if l.startswith("_variant_sets:"))
            pruned, _ = _prune("".join(lines[i + 1:]),
                               lambda k, b: k in DEAD_VARIANT_SETS, indent=2)
            body = "".join(lines[:i + 1]) + pruned
        out.append(body)
    return "".join(out)


def _inject_selections(text, required=True):
    """Add the mask :data:`SELECTION_INJECTIONS` names to the histograms it lists.

    A name that no longer exists upstream raises rather than quietly injecting
    nothing: the whole point of the cut is that those histograms would
    otherwise fill their overflow bin with RPC-first clusters.
    """
    out, seen = [], set()
    for key, body in _blocks(text):
        selection = SELECTION_INJECTIONS.get(key)
        if selection is not None:
            seen.add(key)
            if re.search(r"^  selections: \[", body, re.M):
                body = re.sub(r"^(  selections: \[)", r"\1%s, " % selection,
                              body, count=1, flags=re.M)
            else:
                body = re.sub(r"^(  expression.*\n(?:  per_object.*\n)?)",
                              r"\1  selections: [%s]\n" % selection,
                              body, count=1, flags=re.M)
        out.append(body)
    missing = sorted(set(SELECTION_INJECTIONS) - seen)
    if required and missing:
        raise SystemExit(f"make_rpcmerge_configs: histogram(s) {missing} are gone "
                         "from the reference config -- update SELECTION_INJECTIONS")
    return "".join(out)


def _rewrite_hit_counts(text):
    for old, new in COMMENT_REWRITES:
        text = text.replace(old, new)
    for old, new in HIT_COUNT_REWRITES:
        text = re.sub(r"(?<![\w.])%s(?![\w])" % re.escape(old), new, text)
    for old, new in LABEL_REWRITES:
        text = text.replace(old, new)
    return text


def _generated(text, source):
    """Prepend the do-not-edit banner, after any leading blank lines."""
    return GENERATED_HEADER.format(source=source) + text


def build(source_dir, name):
    """The full file set of one generated config directory."""
    source = source_dir.name
    out = {}

    # columns.yaml: the reference settings plus rpc_merge.
    columns = (source_dir / "columns.yaml").read_text()
    columns = columns.replace("\n  match_min_hits:", COLUMNS_NOTE + "  match_min_hits:", 1)
    out["columns.yaml"] = _generated(columns, source)

    # selections.yaml: drop the RPC-cluster masks, add the RPC-content ones.
    selections, dead_selections = _prune(
        (source_dir / "selections.yaml").read_text(),
        lambda key, body: _mentions(body, DEAD_TOKENS))
    selections = _rewrite_hit_counts(selections) + RPC_SELECTIONS
    out["selections.yaml"] = _generated(selections, source)

    # histograms.yaml: drop the RPC-cluster histograms and everything that
    # selected on a mask that just disappeared; add the RPC timing set.
    histograms = (source_dir / "histograms.yaml").read_text()
    histograms = _prune_variant_sets(histograms)
    histograms, dead_hists = _prune(
        histograms,
        lambda key, body: _mentions(body, DEAD_TOKENS + tuple(dead_selections)))
    histograms = _inject_selections(_rewrite_hit_counts(histograms))
    for sys in ("csc", "dt"):
        histograms += RPC_HISTOGRAMS.format(sys=sys, SYS=sys.upper())
    histograms += CSC_TIME_HISTOGRAMS
    out["histograms.yaml"] = _generated(histograms, source)

    # derived_plots.yaml: drop the plots whose source histograms are gone.
    derived, _ = _prune((source_dir / "derived_plots.yaml").read_text(),
                        lambda key, body: _mentions(body, dead_hists))
    if derived.strip():
        derived += RPC_DERIVED_PLOTS
    out["derived_plots.yaml"] = _generated(derived, source)

    # The rest of the config set is copied verbatim.
    for path in sorted(source_dir.glob("*.yaml")):
        out.setdefault(path.name, path.read_text())
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="only report whether the written configs are current")
    args = parser.parse_args(argv)

    stale = []
    for name, source in SOURCES.items():
        target = CONFIGS / name
        files = build(CONFIGS / source, name)
        if not args.check:
            target.mkdir(exist_ok=True)
        for filename, text in files.items():
            path = target / filename
            if args.check:
                if not path.exists() or path.read_text() != text:
                    stale.append(str(path.relative_to(REPO)))
            else:
                path.write_text(text)
                print(f"wrote {path.relative_to(REPO)}")
    if args.check:
        for path in stale:
            print(f"STALE: {path}")
        print("stale" if stale else "up to date")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
